CREATE TABLE CUSTOMER (
                          ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
                          FIRST_NAME VARCHAR(100) not NULL,
                          LAST_NAME VARCHAR(100) NOT NULL,
                          BIRTH_DATE DATE NOT NULL);

CREATE TABLE COMPANY (
                         ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
                         NAME VARCHAR(100) NOT NULL,
                         COUNTRY_CODE VARCHAR(2));

CREATE TABLE AIRPORT (
                         ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
                         CODE VARCHAR(10) NOT NULL UNIQUE,
                         NAME VARCHAR(100),
                         COUNTRY_CODE VARCHAR(2));

CREATE TABLE FLIGHT (
                        ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
                        NO_FLIGHT VARCHAR(20) NOT NULL UNIQUE,
                        FLIGHT_DATE DATE NOT NULL,
                        FK_COMPANY_ID BIGINT NOT NULL,
                        FK_DEPARTURE_AIRPORT_ID BIGINT NOT NULL,
                        FK_ARRIVAL_AIRPORT_ID BIGINT NOT NULL,
                        FOREIGN KEY (FK_COMPANY_ID) REFERENCES COMPANY(ID),
                        FOREIGN KEY (FK_DEPARTURE_AIRPORT_ID) REFERENCES AIRPORT(ID),
                        FOREIGN KEY (FK_ARRIVAL_AIRPORT_ID) REFERENCES AIRPORT(ID));

CREATE TABLE FLIGHT_VIEW (
                             ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
                             RATING INTEGER,
                             REMARKS VARCHAR(255),
                             ANSWER VARCHAR(255),
                             STATUS VARCHAR(20),
                             CREATION_DATE DATE NOT NULL,
                             MUTATION_DATE DATE,
                             FK_FLIGHT_ID BIGINT NOT NULL,
                             FK_CUSTOMER_ID BIGINT NOT NULL,
                             FOREIGN KEY (FK_FLIGHT_ID) REFERENCES FLIGHT(ID),
                             FOREIGN KEY (FK_CUSTOMER_ID) REFERENCES CUSTOMER(ID));



INSERT INTO COMPANY (name, COUNTRY_CODE)
VALUES ('Air France', 'FR');

INSERT INTO COMPANY (name, COUNTRY_CODE)
VALUES ('Transavia', 'ES');

INSERT INTO COMPANY (name, COUNTRY_CODE)
VALUES ('KLM Royal Dutch Airlines', 'NL');

INSERT INTO COMPANY (name, COUNTRY_CODE)
VALUES ('Swiss', 'CH');

INSERT INTO COMPANY (name, COUNTRY_CODE)
VALUES ('Lufthansa', 'DE');

INSERT INTO AIRPORT (CODE, name, COUNTRY_CODE)
VALUES ('TLS', 'Toulouse', 'FR');

INSERT INTO AIRPORT (CODE, name, COUNTRY_CODE)
VALUES ('ORY', 'Paris Orly', 'FR');

INSERT INTO AIRPORT (CODE, name, COUNTRY_CODE)
VALUES ('CDG', 'Paris CDG', 'FR');

INSERT INTO AIRPORT (CODE, name, COUNTRY_CODE)
VALUES ('GVA', 'Geveva', 'CH');

INSERT INTO AIRPORT (CODE, name, COUNTRY_CODE)
VALUES ('BER', 'Berlin', 'DE');

INSERT INTO AIRPORT (CODE, name, COUNTRY_CODE)
VALUES ('MAD', 'Madrid', 'ES');

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('John', 'Doe', date '2001-09-28');

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Matthieu', 'Schittly', date '1982-03-25');

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Elisabeth', 'Dupont', date '1986-11-01');

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Jean-Marc', 'Dupond', date '1955-12-09');

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Terence', 'Hill', date '1950-01-01');

INSERT INTO FLIGHT (NO_FLIGHT, FLIGHT_DATE, FK_COMPANY_ID, FK_DEPARTURE_AIRPORT_ID, FK_ARRIVAL_AIRPORT_ID)
SELECT '11111', date '2025-01-05', C.ID, A1.ID, A2.ID
FROM AIRPORT A1
LEFT JOIN AIRPORT A2 ON A2.CODE = 'CDG'
LEFT JOIN COMPANY C ON UPPER(C.NAME) = 'AIR FRANCE'
WHERE A1.CODE = 'TLS';

INSERT INTO FLIGHT (NO_FLIGHT, FLIGHT_DATE, FK_COMPANY_ID, FK_DEPARTURE_AIRPORT_ID, FK_ARRIVAL_AIRPORT_ID)
SELECT '22222', date '2025-02-17', C.ID, A1.ID, A2.ID
FROM AIRPORT A1
LEFT JOIN AIRPORT A2 ON A2.CODE = 'ORY'
LEFT JOIN COMPANY C ON UPPER(C.NAME) = 'TRANSAVIA'
WHERE A1.CODE = 'GVA';

INSERT INTO FLIGHT (NO_FLIGHT, FLIGHT_DATE, FK_COMPANY_ID, FK_DEPARTURE_AIRPORT_ID, FK_ARRIVAL_AIRPORT_ID)
SELECT '33333', date '2025-03-18', C.ID, A1.ID, A2.ID
FROM AIRPORT A1
LEFT JOIN AIRPORT A2 ON A2.CODE = 'BER'
LEFT JOIN COMPANY C ON UPPER(C.NAME) = 'LUFTHANSA'
WHERE A1.CODE = 'CDG';

INSERT INTO FLIGHT (NO_FLIGHT, FLIGHT_DATE, FK_COMPANY_ID, FK_DEPARTURE_AIRPORT_ID, FK_ARRIVAL_AIRPORT_ID)
SELECT '44444', date '2025-05-25', C.ID, A1.ID, A2.ID
FROM AIRPORT A1
LEFT JOIN AIRPORT A2 ON A2.CODE = 'GVA'
LEFT JOIN COMPANY C ON UPPER(C.NAME) LIKE 'KLM%'
WHERE A1.CODE = 'BER';

INSERT INTO FLIGHT (NO_FLIGHT, FLIGHT_DATE, FK_COMPANY_ID, FK_DEPARTURE_AIRPORT_ID, FK_ARRIVAL_AIRPORT_ID)
SELECT '55555', date '2025-05-25', C.ID, A1.ID, A2.ID
FROM AIRPORT A1
LEFT JOIN AIRPORT A2 ON A2.CODE = 'GVA'
LEFT JOIN COMPANY C ON UPPER(C.NAME) = 'SWISS'
WHERE A1.CODE = 'TLS';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 5, 'Good experience', 'Thank you for your feedback', 'PUBLISHED', '2025-06-01 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'DOE'
WHERE F.NO_FLIGHT = '11111';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 3, 'Quite good flight', null, 'PENDING', '2025-06-01 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'HILL'
WHERE F.NO_FLIGHT = '11111';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 4, 'Super!', null, 'PROCESSED', '2025-06-01 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'SCHITTLY'
WHERE F.NO_FLIGHT = '11111';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 1, 'Hey dude that is a fake comment', null, 'REJECTED','2025-06-01 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'HILL'
WHERE F.NO_FLIGHT = '22222';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 4, 'Good', 'Thanks for your positive comment', 'PUBLISHED', '2025-06-01 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'DUPONT'
WHERE F.NO_FLIGHT = '22222';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 3, 'Okay', null, 'PROCESSED', '2025-06-02 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'DUPOND'
WHERE F.NO_FLIGHT = '22222';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 4, 'Marvellous experience', 'Thank you', 'PUBLISHED', '2025-06-02 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'HILL'
WHERE F.NO_FLIGHT = '33333';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 3, 'Okay', null, 'PROCESSED', '2025-06-03 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'DUPOND'
WHERE F.NO_FLIGHT = '33333';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 5, 'I really enjoyed this flight', null, 'PUBLISHED', '2025-06-03 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'DOE'
WHERE F.NO_FLIGHT = '33333';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 3, '...', null, 'REJECTED', '2025-06-04 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'DUPONT'
WHERE F.NO_FLIGHT = '44444';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 5, 'SUPER!', null, 'PROCESSED', '2025-06-04 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'SCHITTLY'
WHERE F.NO_FLIGHT = '44444';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 3, 'OK', null, 'PROCESSED', '2025-06-05 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'DOE'
WHERE F.NO_FLIGHT = '55555';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 5, 'SUPER!', 'Thank you for your feedback', 'PROCESSED', '2025-06-05 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'HILL'
WHERE F.NO_FLIGHT = '55555';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 3, 'Okay', 'Thank you for your feedback', 'PUBLISHED', '2025-06-06 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'DUPONT'
WHERE F.NO_FLIGHT = '55555';

INSERT INTO FLIGHT_VIEW (RATING, REMARKS, ANSWER, STATUS, CREATION_DATE, FK_FLIGHT_ID, FK_CUSTOMER_ID)
SELECT 4, 'Great trip', 'Thank you for your feedback', 'PUBLISHED', '2025-06-06 09:00:00', F.ID, C.ID
FROM FLIGHT F
         LEFT JOIN CUSTOMER C ON Upper(C.LAST_NAME) = 'DOE'
WHERE F.NO_FLIGHT = '55555';