server:
  port: 8080
  servlet:
    context-path: /flights
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 2
      connection-timeout: 20000
      minimum-idle: 2
    url: jdbc:postgresql://localhost:5432/test_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    data:
      jpa:
        repositories:
          enabled: true
    security:
      user:
        password: user
        name: password